apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-default
  template:
    metadata:
      labels:
        app: extractor-default
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_GROUP
              value: "DEFAULT"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
          # readinessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-1
  template:
    metadata:
      labels:
        app: extractor-1
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_GROUP
              value: "1"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
          # readinessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-56
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-56
  template:
    metadata:
      labels:
        app: extractor-56
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_GROUP
              value: "56"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
          # readinessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-137
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-137
  template:
    metadata:
      labels:
        app: extractor-137
    spec:
      containers:
        - name: extractor
          image: extractor:latest
          ports:
            - containerPort: 80
          env:
            - name: CONFIG_GROUP
              value: "137"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: extractor
                  key: DRPC_ID
          # readinessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 5