apiVersion: v1
kind: Service
metadata:
  name: extractor-1-service
spec:
  selector:
    app: extractor-1
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: extractor-56-service
spec:
  selector:
    app: extractor-56
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: extractor-default-service
spec:
  selector:
    app: extractor-default
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080