apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: extractor-staging-ingress
  annotations:
    kubernetes.io/ingressClassName: "nginx"
    kubernetes.io/ingress.global-static-ip-name: "extractor-staging-ip"
    networking.gke.io/managed-certificates: "extractor-staging-managed-certificate"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: extractor-staging-managed-certificate
spec:
  domains:
    - staging.sushi.com