apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </html>
  nginx.conf: |
    events {
      worker_connections 4096;
    }
    http { 
      upstream extractor-1 {server extractor-1-service;}
      upstream extractor-56 {server extractor-56-service;}
      upstream extractor-137 {server extractor-137-service;}
      upstream extractor-default {server extractor-default-service;}
      map $arg_chainId $proxy_pass {
        1       extractor-1;
        56      extractor-56;
        137     extractor-137;
        default extractor-default;
      }
      server { 
        listen 80; 
        location / {
          proxy_pass http://$proxy_pass;
        } 
      } 
    }