apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data: 
  # nginx.conf: 'events {} http { map $arg_chainId $proxy_pass { 1 http://extractor-1-service:8080; 56 http://extractor-56-service:8080; } server { listen 80; resolver kubernetes.default.svc.cluster.local; location / { proxy_pass $proxy_pass; } location /test/ { proxy_pass http://extractor-1-service:8080/; } location /test2/ { proxy_pass http://extractor-56-service:8080/; } } }'
  nginx.conf: |
    events {} 
    http { 

      upstream extractor-1 {server extractor-1-service;}
      upstream extractor-56 {server extractor-56-service;}
      upstream extractor-137 {server extractor-137-service;}
      upstream extractor-default {server extractor-default-service;}

      map $arg_chainId $backend {
          1       extractor-1;
          56      extractor-56;
          137     extractor-137;
          default extractor-default;
      }

      server { 
        listen 80; 
        location / { 
          proxy_redirect          http:// https://;
          proxy_pass              http://$backend;
        } 
      } 
    }