apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: extractor-1-service
spec:
  selector:
    app: extractor-1
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: 'events {} http { map $arg_chainId $extractor_ip { default http://extractor-1-service:8080/; } server { listen 80; location / { proxy_pass $extractor_ip; } location /test { proxy_pass http://www.sushi.com/; } } }'