apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sushi-api-staging-ingress
  annotations:
    kubernetes.io/ingressClassName: "nginx"
    kubernetes.io/ingress.global-static-ip-name: "sushi-api-staging-ip"
    networking.gke.io/managed-certificates: "sushi-api-staging-managed-certificate"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  gzip-level: "5"
  gzip-types: application/json
  use-gzip: "true"
