apiVersion: batch/v1
kind: CronJob
metadata:
  name: pull-cache
spec:
  schedule: "0 1 * * *" # run every day at 1am
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: extractor
          containers:
          - name: pull-cache
            image: google/cloud-sdk
            args:
            - gsutil
            - -m
            - cp
            - -r
            - gs://extractor-cache/*
            - cache
            volumeMounts:
            - mountPath: /cache
              name: extractor-pv
          restartPolicy: OnFailure
          volumes:
          - name: extractor-pv
            persistentVolumeClaim:
              claimName: extractor-pvc