apiVersion: batch/v1
kind: CronJob
metadata:
  name: push-cache
spec:
  schedule: "0 0 * * *" # run every day at midnight
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: extractor
          containers:
          - name: push-cache
            image: google/cloud-sdk
            args:
            - gsutil
            - -m
            - cp
            - -r
            - cache/*
            - gs://extractor-cache
            volumeMounts:
            - mountPath: /cache
              name: extractor-pv
          restartPolicy: OnFailure
          volumes:
          - name: extractor-pv
            persistentVolumeClaim:
              claimName: extractor-pvc