apiVersion: batch/v1
kind: CronJob
metadata:
  name: push-cache
spec:
  schedule: "*/5 * * * *" # run every 5 minutes to test
  # schedule: "0 0 * * *" # run every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: extractor
          containers:
          - name: push-cache
            image: google/cloud-sdk
            imagePullPolicy: IfNotPresent
            command:
            - gsutil -m cp -r cache/* gs://extractor-cache
          volumeMounts:
          - mountPath: /cache
            name: extractor-pv
          restartPolicy: OnFailure
          volumes:
          - name: extractor-pv
            persistentVolumeClaim:
              claimName: extractor-pvc