

{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: extractor-{{ $value }}-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: extractor-{{ $value }}
  updatePolicy:
    updateMode: "Auto"
{{- end }}