{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: extractor-{{ $value }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: /cache/extractor-{{ $value }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extractor-{{ $value }}-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-{{ $value }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-{{ $value }}
  template:
    metadata:
      labels:
        app: extractor-{{ $value }}
    spec:
      containers:
        - name: extractor
          image: extractor
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /app/cache
              name: extractor-{{ $value }}-pv
          # volumeMounts:
          # - name: extractor-{{ $value }}-volume
          #   mountPath: /app/cache
          env:
            - name: CHAIN_ID
              value: "{{ $value }}"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: DRPC_ID
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_ENVIRONMENT
      volumes:
        - name: extractor-{{ $value }}-pv
          persistentVolumeClaim:
            claimName: extractor-{{ $value }}-pvc
      # volumes:
      # - name: extractor-{{ $value }}-volume
      #   hostPath:
      #     path: /cache/extractor-{{ $value }}
{{- end }}