{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extractor-{{ $value }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-{{ $value }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-{{ $value }}
  template:
    metadata:
      labels:
        app: extractor-{{ $value }}
    spec:
      containers:
        - name: extractor
          image: extractor
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /app/cache
              name: extractor-{{ $value }}-pv-storage
          env:
            - name: CHAIN_ID
              value: "{{ $value }}"
            - name: DRPC_ID
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: DRPC_ID
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: sushi-api
                  key: SENTRY_ENVIRONMENT
      volumes:
        - name: extractor-{{ $value }}-pv-storage
          persistentVolumeClaim:
            claimName: extractor-{{ $value }}-pvc
{{- end }}