apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 4096;
    }
    http { 
      {{- $chainIds := .Values.chainIds }}
      {{- range $index, $value := $chainIds }}
      upstream router-{{ $value }} {
        server router-{{ $value }};
      }
      {{- end }}
      
      map $uri $proxy_pass {
        ~^/(\w+)/(\w+)/(\d+) router-$3;
      }
      
      server { 
        listen 80;
        location / {
          proxy_pass http://$proxy_pass;
        }
        location /health {
          auth_basic off;
          return 200;
        }
      } 
    }