{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: router-{{ $value }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: router-{{ $value }}
  minReplicas: 10
  maxReplicas: 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
{{- end }}

