{{- $chainIds := .Values.chainIds }}
{{- range $index, $value := $chainIds }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: router-{{ $value }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: router-{{ $value }}
  minReplicas: 1
  maxReplicas: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 1000
        periodSeconds: 3
      # - type: Pods
      #   value: 4
      #   periodSeconds: 3
      selectPolicy: Max
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
{{- end }}

