apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: extractor
description: extractor pipeline
serialPipeline:
  stages:
  - targetId: development
    profiles: []
  - targetId: production
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: development
description: development cluster
gke:
  cluster: projects/extractor-410208/locations/us-east4/clusters/development
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: production cluster
gke:
  cluster: projects/extractor-410208/locations/us-central1/clusters/production