apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: sushiswap
build:
  artifacts:
    - image: extractor
      context: ../../
      docker:
        dockerfile: Dockerfile
        buildArgs:
          SCRIPT_PATH: "./apis/extractor"
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml

