# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: extractor-1
deploy:
  kubectl:
    manifests:
    - k8s/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}